### PR TITLE
Fixed wrong sentence

### PR DESCRIPTION
**Pull request by StefanKert**
Added missing word to description

### CODE REVIEW

**Comment by v-tisip** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo because branch live has been deleted.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C21%5C24d9c583-6d22-8270-40c1-cb4ea764d86d%5CPullRequest%5C201710210717206154-6%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=3YcRQgP6b5GNFET9LLmV%2Byp7BYm9ERbz6z%2BDcgBjaD8%3D&st=2017-10-21T07%3A12%3A25Z&se=2017-11-21T07%3A17%3A25Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by StefanKert** [comment]
Changed PR to merge to master branch. Is it possible to sync the checks?

**Comment by gosali** [comment]
Hi @StefanKert, we are still in discussing, will update the decision later soon. 
All contributions must be submitted in the Live branch.
 
Thanks for your support,
Microsoft C&E Localization Team

**Comment by gosali** [comment]
@StefanKert , Thank you for your feedback and suggestion! 
  
The suggestion will be merged to the production, we will re-release this articles in the next loc release round. 
  
Microsoft C&E Localization Team

**Pull request merged**
