### PR TITLE
Fixes #12: Over-localization of Razor-Pages

### LINKED ISSUE #12: Over-localization of Razor-Pages
The term "Razor-pages" shouldn't be translated into "Razor-Seiten".
e.g. https://docs.microsoft.com/de-de/aspnet/core/tutorials/razor-pages/

Germans usually don't translate identifier and names. In this case Razor-Pages is a name of a Technologie. So it is absolutely fine to not translate Razor-Pages-Web-App into Razor-Seiten-Web-App.

I would take care of the fix, if you agree.

### PR DESCRIPTION
**Pull request by JuergenGutsch**
This PR fixes #12

### CODE REVIEW

**Comment by CeciAc** [comment]
Closing this issue since it's being fixed in the commented PR #12 
Sincerely, Microsoft C & E Localization Team

**Comment by JuergenGutsch** [comment]
Hi @CeciAc,
you just closed the PR instead of the issue ;-)
I planned to fix the merge conflicts these days during the MVP Summit.
Would you reopen the PR and close the Issue instead? Thanks :-)

**Comment by CeciAc** [comment]
Oops, sorry and good to hear that! :)

**Comment by JuergenGutsch** [comment]
Hi @CeciAc,
the conflicts are fixed now.

**Comment by gosali** [comment]
Hi @JuergenGutsch , Thank you for your feedback and suggestion! 
  
The suggestion will be implemented by the production team, we will close this PR since it was submitted in the master branch. 

Microsoft C&E Localization Team

**Pull request closed without merging**
