### PR TITLE
Improve machine-translation

### PR DESCRIPTION
**Pull request by awaitJosh**
Part 1

### CODE REVIEW

**Comment by v-tisip** [comment]
### :white_check_mark: Validation status: partially passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[aspnetcore/tutorials/razor-pages-vsc/model.md](https://github.com/awaitJosh/Docs.de-de/blob/patch-2/aspnetcore/tutorials/razor-pages-vsc/model.md) | :x:Error | [View](https://review.docs.microsoft.com/de-de/aspnet/core/tutorials/razor-pages-vsc/model?branch=pr-de-de-7) | [Details](#user-content-aspnetcore%2Ftutorials%2Frazor-pages-vsc%2Fmodel.md)
[aspnetcore/publishing/development-time-iis-support.md](https://github.com/awaitJosh/Docs.de-de/blob/patch-2/aspnetcore/publishing/development-time-iis-support.md) | :warning:Warning | [View](https://review.docs.microsoft.com/de-de/aspnet/core/publishing/development-time-iis-support?branch=pr-de-de-7) | [Details](#user-content-aspnetcore%2Fpublishing%2Fdevelopment-time-iis-support.md)
[aspnetcore/publishing/visual-studio-tools-for-docker.md](https://github.com/awaitJosh/Docs.de-de/blob/patch-2/aspnetcore/publishing/visual-studio-tools-for-docker.md) | :warning:Warning | [View](https://review.docs.microsoft.com/de-de/aspnet/core/publishing/visual-studio-tools-for-docker?branch=pr-de-de-7) | [Details](#user-content-aspnetcore%2Fpublishing%2Fvisual-studio-tools-for-docker.md)
[aspnetcore/tutorials/razor-pages/uploading-files.md](https://github.com/awaitJosh/Docs.de-de/blob/patch-2/aspnetcore/tutorials/razor-pages/uploading-files.md) | :warning:Warning | [View](https://review.docs.microsoft.com/de-de/aspnet/core/tutorials/razor-pages/uploading-files?branch=pr-de-de-7) | [Details](#user-content-aspnetcore%2Ftutorials%2Frazor-pages%2Fuploading-files.md)
[aspnetcore/mvc/controllers/actions.md](https://github.com/awaitJosh/Docs.de-de/blob/patch-2/aspnetcore/mvc/controllers/actions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/de-de/aspnet/core/mvc/controllers/actions?branch=pr-de-de-7) |

<a name="aspnetcore%2Ftutorials%2Frazor-pages-vsc%2Fmodel.md"></a>
### [aspnetcore/tutorials/razor-pages-vsc/model.md](https://github.com/awaitJosh/Docs.de-de/blob/patch-2/aspnetcore/tutorials/razor-pages-vsc/model.md)
 - **Line 12**: **[Error]** Start line 19 exceeds total lines 15 when resolving &quot;[!code-csharp[Main](../../tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie/Models/MovieContext.cs?range=1-12,14-17,19-21)]&quot;

<a name="aspnetcore%2Fpublishing%2Fdevelopment-time-iis-support.md"></a>
### [aspnetcore/publishing/development-time-iis-support.md](https://github.com/awaitJosh/Docs.de-de/blob/patch-2/aspnetcore/publishing/development-time-iis-support.md)
 - **Line 35**: **[Warning]** Invalid file link:(~/publishing/development-time-iis-support/_static/enable_iis.png).
 - **Line 43**: **[Warning]** Invalid file link:(~/publishing/development-time-iis-support/_static/development_time_support.png).
 - **Line 49**: **[Warning]** Invalid file link:(~/publishing/development-time-iis-support/_static/project_properties.png).

<a name="aspnetcore%2Fpublishing%2Fvisual-studio-tools-for-docker.md"></a>
### [aspnetcore/publishing/visual-studio-tools-for-docker.md](https://github.com/awaitJosh/Docs.de-de/blob/patch-2/aspnetcore/publishing/visual-studio-tools-for-docker.md)
 - **Line 39**: **[Warning]** Invalid file link:(~/publishing/visual-studio-tools-for-docker/_static/settings-shared-drives-win.png).
 - **Line 47**: **[Warning]** Invalid file link:(~/publishing/visual-studio-tools-for-docker/_static/project-add-docker-support.png).
 - **Line 51**: **[Warning]** Invalid file link:(~/publishing/visual-studio-tools-for-docker/_static/right-click-add-docker-support.png).

<a name="aspnetcore%2Ftutorials%2Frazor-pages%2Fuploading-files.md"></a>
### [aspnetcore/tutorials/razor-pages/uploading-files.md](https://github.com/awaitJosh/Docs.de-de/blob/patch-2/aspnetcore/tutorials/razor-pages/uploading-files.md)
 - **Line 53**: **[Warning]** Invalid file link:(~/tutorials/first-mvc-app/adding-model/_static/pmc.png).
 - **Line 128**: **[Warning]** Invalid file link:(~/tutorials/razor-pages/uploading-files/_static/browser1.png).
 - **Line 132**: **[Warning]** Invalid file link:(~/tutorials/razor-pages/uploading-files/_static/browser2.png).
 - **Line 136**: **[Warning]** Invalid file link:(~/tutorials/razor-pages/uploading-files/_static/browser3.png).
 - **Line 140**: **[Warning]** Invalid file link:(~/tutorials/razor-pages/uploading-files/_static/browser4.png).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C24%5C24d9c583-6d22-8270-40c1-cb4ea764d86d%5CPullRequest%5C201710241136585833-7%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=LUgO0RaEK%2Fw19eMzw4mK7qzwpobGnFZ5LjiA%2BVJwD7w%3D&st=2017-10-24T11%3A34%3A40Z&se=2017-11-24T11%3A39%3A40Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-radelg** [comment]
Hi @awaitJosh , we are still in discussing, will update the decision later soon. 
		
Thanks for your support,

Microsoft C&E Localization Team

**Comment by awaitJosh** [comment]
Hi @v-radelg ,

thanks for your answer! I´m curious to see, what happens with my pull-request. 

The machine-translation is a good starting point, but vocabulary and syntax is somehow convoluted. I want to give something back to you and all your effort. Right now I am not sophisticated enough to provide some code - but translations are in my scope, I think.

If you are somehow able to validate changes in a foreign language (and if you and your team is interested in translation improvement), I´ll continue. If I can do something, to make better pull-requests or anything similar, please let me know :)

Best regards

**Comment by v-radelg** [comment]
@awaitJosh : Thank you for your feedback and suggestion! 

The feedback is considered. We will tune part of  your feedback in order to comply with Microsoft Style Guide, then release this article in the next loc release round.
		
Microsoft C&E Localization Team

**Comment by v-tisip** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **Line 356**: **[Error]** Error happened in build.entrypoint.ps1. Please build your target branch first and then reopen this pull request to do another round of verification. If the issue still happens, open a ticket in http://SiteHelp and include the following error message for our team to troubleshoot: The process cannot access the file &#39;tmp_pack_TSpdTa&#39; because it is being used by another process.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C27%5C24d9c583-6d22-8270-40c1-cb4ea764d86d%5CPullRequest%5C201710271951209627-7%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=oLAvndBpFEKHiNX9P8NVJUI5BS6tSvZB7NEZwVLZGGs%3D&st=2017-10-27T20%3A00%3A12Z&se=2017-11-27T20%3A05%3A12Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
